#.PHONY: run clean

# Regla por defecto
default: run

# Regla para ejecutar main.py
run:
	python3 main.py

# Regla para limpiar archivos generados
clean:
	rm BarOraculo.txt \
	&& rm Isla_de_las_Sombras.txt \
	&& rm Isla_del_Dragon_Rojo.txt \
	&& rm Isla_de_las_Estrellas.txt \
	&& rm Isla_del_Bosque_Encantado.txt \
	&& rm Isla_de_los_Susurros.txt \
	&& rm Isla_del_Trueno.txt \
	&& rm Isla_del_Tesoro_Oculto.txt \
	&& rm Salida.txt
